---
- name: Create Vault configuration directory
  file:
    path: "{{ vault_config_dir }}"
    state: directory
    mode: '0755'

- name: Get private IP using hostname and manipulate with sed
  shell: "hostname | sed 's/ip-//; s/-/./g'"
  register: private_ip_result

- name: Set the private IP as a variable
  set_fact:
    PRIVATE_IP: "{{ private_ip_result.stdout }}"

- name: Add Vault configuration
  copy:
    dest: "{{ vault_config_file }}"
    content: |
      storage "file" {
        path = "{{ vault_data_dir }}"
      }
      listener "tcp" {
        address     = "0.0.0.0:8200"
        tls_disable = 1
      }

      # API Address Configuration
      api_addr = "http://{{ PRIVATE_IP }}:8200"  

      disable_mlock = true
      ui = true
