---
- name: Create Vault configuration directory
  file:
    path: "{{ vault_config_dir }}"
    state: directory
    mode: '0755'

- name: Add Vault configuration
  copy:
    dest: "{{ vault_config_file }}"
    content: |
      storage "file" {
        path = "{{ vault_data_dir }}"
      }
      listener "tcp" {
        address     = "0.0.0.0:8200"
        tls_disable = 1
      }

      # API Address Configuration
      api_addr = "http://127.0.0.1:8200"  

      disable_mlock = true
      ui = true
